name: WDLCompanionFactionsSupport
main: wdl.factions.FactionsSupportPlugin
version: 0.0.1
author: Pokechu22
depend: [WDLCompanion, Factions]
website: http://dev.bukkit.org/bukkit-plugins/wdl-companion-factions-support
description: Adds 2 new WDLCompanion ChunkOverride types, 'Owned faction' and 'Nearby factions', which allow a player to download in their own faction or nearby factions they have permission in.  Also defines some user-toggleable permissions so that each faction can choose who can download.